# Generated by Django 5.0.4 on 2024-05-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_bitcointransaction_aggregate_feature_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bitcointransaction",
            name="description",
        ),
    ]
