# Generated by Django 5.0.4 on 2024-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_bitcointransaction_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitcointransaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
