# Generated by Django 5.0.4 on 2024-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_bitcointransaction_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitcointransaction",
            name="isConfirmed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="bitcointransaction",
            name="isFraud",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
