# Generated by Django 5.0.4 on 2024-06-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_bitcointransaction_isconfirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitcointransaction",
            name="tx_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
